### ISSUE TITLE
Publish v5.2.0

### ISSUE THREAD

**Issue by junderw** [cryptocoinjs/coininfo#102]
I went ahead and reviewed open PRs.

- Older ones/stale ones were closed and can be reopened if needed.
- Ones with conflicts were closed with comments to fix.

**Comment by sondreb** [comment]
The PR for City Coin was re-added #103 and hope it can be included before the release. Thanks!

**Comment by gruve-p** [comment]
@junderw Any plans to publish v5.2.0 anytime soon?
@RoukePouw needs it for https://github.com/hybrix-io/deterministic/pull/30

**Comment by junderw** [comment]
No clue.

I don't have publish rights

**Comment by junderw** [comment]
I recommend installing from github by referencing a specific commit

**Comment by gruve-p** [comment]
Who has the publish rights and do they need to move to you?

**Comment by junderw** [comment]
https://www.npmjs.com/package/coininfo

There's about 7 people.
I was given commit rights to the Github organization for cryptocoinjs, which implicitly gives me permission for this repository.
However, npm is really hard to manage package rights, it's not intuitive, and you can't "link" a Github / Gitlab account etc.

**Comment by gruve-p** [comment]
ping @fanatid

**Comment by fanatid** [comment]
I added @junderw to coininfo owners. Thanks for the ping @gruve-p :+1:

**Comment by gruve-p** [comment]
@junderw Can you publish v5.2.0 and close this issue please?

**Comment by junderw** [comment]
@gruve-p Published 5.2.0 then 5.2.1 with latest master.
