### ISSUE TITLE
Add genesis block hash

### ISSUE THREAD

**Issue by runn1ng** [cryptocoinjs/coininfo#26]
It would be useful (at least to us, but maybe to others too) to include hash of genesis blocks as one of the constants.

Why do we need it... we are building a "universal" web wallet, where you just plug-in bitcore URL, it grabs block with ID 0 and it continues based on that.

I think it would be better to add this to coininfo rather than build it on our own.

**Comment by jprichardson** [comment]
Published 0.9.0. Thanks for https://github.com/cryptocoinjs/coininfo/issues/27!

**Comment by runn1ng** [comment]
Thanks for merging and publishing! That was fast!
