### ISSUE TITLE
More network info

### ISSUE THREAD

**Issue by stuartpb** [cryptocoinjs/coininfo#5]
It seems like I would need this info to connect to the Bitcoin / Litecoin / Dogecoin network: https://github.com/bitpay/bitcore/blob/master/networks.js

I mean, just looking at the p2p-manager guide, it looks like it needs a list of seeds, and if I'm looking to join the Dogecoin network, I have no idea how I'd go about that.

Reading #1, it looks like https://github.com/dogecoin/dogecoin/blob/master/src/chainparams.cpp is the place to find Dogecoin's network info.

**Comment by jprichardson** [comment]
Done https://github.com/cryptocoinjs/coininfo/releases/tag/0.3.0. Doesn't specifically include Litecoin or Dogecoin info yet, but you can see the canonical example: https://github.com/cryptocoinjs/coininfo/blob/master/lib/coins/btc.js
