### ISSUE TITLE
Where do you get the versions information for different coins? 

### ISSUE THREAD

**Issue by SethMcGuire** [cryptocoinjs/coininfo#52]
// base58Prefixes
  versions: {
    bip32: {
      private: 0x0488ade4,
      public: 0x0488b21e
    },
    bip44: 2301,
    private: 0x80,
    public: 0x3A,
    scripthash: 0x32
  }

I'd like to find that information for several different coins that aren't on coininfo so I can add them to a bitcoinjs project.

**Comment by fanatid** [comment]
All what you pasted here located in source code, except bip44 what is located here: https://github.com/satoshilabs/slips/blob/master/slip-0044.md

**Comment by SethMcGuire** [comment]
In the source code of each coin? That's a ton of code, do you know where exactly I might find that for bitcoin cash?

**Comment by cenyG** [comment]
for example we have btc data here:  
// base58Prefixes
  versions: {
    bip32: {
      private: 0x0488ade4,
      public: 0x0488b21e
    },
    bip44: 0,
    private: 0x80,
    public: 0x00,
    scripthash: 0x05
  }
and code here:
https://github.com/bitcoin/bitcoin/blob/master/src/chainparams.cpp
For me it is not obvious how to get this data from this code.

**Comment by fanatid** [comment]
https://github.com/bitcoin/bitcoin/blob/f66e1c793eda7a6143fd03400c98512a9b6f00c7/src/chainparams.cpp#L140-L144

**Comment by cenyG** [comment]
cool, very fast , thnx
